# Generated by Django 2.0.4 on 2018-05-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='requesting_or_offering',
            new_name='requesting',
        ),
    ]
